version: "3"

services:
  fuel-core:
    platform: linux/amd64
    container_name: "${PROJECT:-fuel-node}_fuel-core"
    environment:
      FUEL_IP: ${FUEL_IP}
      FUEL_CORE_PORT: ${FUEL_CORE_PORT}
      NETWORK_NAME: "${PROJECT} local"
      MIN_GAS_PRICE: ${MIN_GAS_PRICE}
      CONSENSUS_KEY_SECRET: ${WALLET_SECRET}
    build: ./fuel-core
    ports:
      - "${FUEL_CORE_PORT:-4000}:4000"
    volumes:
      - fuel-core-db:/mnt/db
    healthcheck:
      test: curl --fail http://localhost:4000/v1/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 20
    networks:
      - bako-network

  faucet:
    platform: linux/amd64
    container_name: "${PROJECT:-fuel-node}_faucet"
    environment:
      MIN_GAS_PRICE: ${MIN_GAS_PRICE}
      WALLET_SECRET_KEY: ${WALLET_SECRET}
      DISPENSE_AMOUNT: ${DISPENSE_AMOUNT}
      FUEL_NODE_URL: http://${PROJECT:-fuel-node}_fuel-core:4000/v1/graphql
    image: ghcr.io/fuellabs/faucet:4f7bec0
    ports:
      - "${FUEL_FAUCET_PORT:-4040}:3000"
    links:
      - fuel-core
    depends_on:
      fuel-core:
        condition: service_healthy
    networks:
      - bako-network

volumes:
  fuel-core-db:
    name: "${PROJECT:-fuel-node}_fuel-core-db"

networks:
  bako-network:
    external: true
