FROM node:18.14.2

# Define o diretório de trabalho no contêiner
WORKDIR /api

# Copia os arquivos do projeto para o diretório de trabalho no contêiner
COPY . .

# Instala as dependências do projeto
RUN yarn install

# Instala o pm2 globalmente
RUN yarn global add pm2

# Compila o projeto
RUN yarn build

# Expõe a porta que a API usará
EXPOSE 3333

ENTRYPOINT ["yarn", "start"]