version: "3"
services:
  api:
    container_name: ${WORKER_NAME}
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /api
    environment:
      - API_ENVIRONMENT=${API_ENVIRONMENT}
      # PSQL
      - WORKER_DATABASE_HOST=${WORKER_DATABASE_HOST}
      - WORKER_DATABASE_PORT=${WORKER_DATABASE_PORT}
      - WORKER_DATABASE_USERNAME=${WORKER_DATABASE_USERNAME}
      - WORKER_DATABASE_PASSWORD=${WORKER_DATABASE_PASSWORD}
      - WORKER_DATABASE_NAME=${WORKER_DATABASE_NAME}
      #MONGO
      - WORKER_MONGO_HOST=${WORKER_MONGO_HOST}
      - WORKER_MONGO_PORT=${WORKER_MONGO_PORT}
      - WORKER_MONGO_USERNAME=${WORKER_MONGO_USERNAME}
      - WORKER_MONGO_PASSWORD=${WORKER_MONGO_PASSWORD}
      # REDIS
      - WORKER_REDIS_HOST=${WORKER_REDIS_HOST}
      - WORKER_REDIS_PORT=${WORKER_REDIS_PORT}
      # APP
      - WORKER_NAME=${WORKER_NAME}
      - WORKER_PORT=${WORKER_PORT}
