name: "[WORKER] Deploy to Amazon ECS"

on:
  push:
    branches:
      - FEAT/index-vaaul-balance

env:
  PACKAGE_NAME: "worker"
  CLUSTER_NAME: "Bako-Safe-ECS"

jobs:
  check-changes:
    name: "Check for Changes"
    runs-on: ubuntu-latest

    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set dynamic environment variables
        run: |
          echo "BASE_PATH=./packages/${{ env.PACKAGE_NAME }}" >> $GITHUB_ENV
          echo "TASK_DEF_PATH=$BASE_PATH/task_def.json" >> $GITHUB_ENV
          echo "SERVICE_NAME=bako-safe-${{ env.PACKAGE_NAME }}-service" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=bako-safe-${{ env.PACKAGE_NAME }}" >> $GITHUB_ENV

      - name: Check for changes in ${{ env.PACKAGE_NAME }}
        id: check
        run: |
          if git diff --quiet HEAD~1 -- $BASE_PATH; then
            echo "No changes detected in $BASE_PATH"
            echo "::set-output name=should_deploy::false"
          else
            echo "Changes detected in $BASE_PATH"
            echo "::set-output name=should_deploy::true"
          fi

  deploy:
    name: "[WORKER] Deploy to Amazon ECS"
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.should_deploy == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BAKO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BAKO_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: $ECR_REPOSITORY
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $BASE_PATH
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: $TASK_DEF_PATH
          service: $SERVICE_NAME
          cluster: ${{ env.CLUSTER_NAME }}
          wait-for-service-stability: true
